version: '2'

services:

  ldap:
    image: osixia/openldap:1.1.8
    hostname: ldap
    volumes:
        - ./ldap_entries:/ldap_entries/

  ldapadmin:
    image: osixia/phpldapadmin:0.7.1
    hostname: phpldapadmin-service
    links:
      - ldap:ldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldapadmin"
      PHPLDAPADMIN_HTTPS=false:

  php:
    build: php5.4-apache
    ports:
     - 80:80
    volumes:
     - ./code:/var/www/html
