version: '2'

services:

  ldap:
    image: osixia/openldap:1.1.8
    container_name: ldap
    hostname: ldap
    network_mode: "host"
    ports:
      - 389:389
      - 636:636
    volumes:
      - ./ldap_entries:/ldap_entries/

  ldapadmin:
    image: osixia/phpldapadmin:0.7.1
    hostname: ldapadmin
    links:
      - ldap:ldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldapadmin"
      PHPLDAPADMIN_HTTPS=false:

  php:
    build: php5.4-apache
    ports:
     - 80:80
    volumes:
     - ./src:/var/www/html
